run:
  timeout: 5m

linters:
  enable:
    - revive

issues:
  max-issues-per-linter: 0 # Show all issues
  max-same-issues: 0 # No limit on repeating issues

output:
  print-issued-lines: true
  print-linter-name: true

# Ensure warnings do not fail CI
severity:
  default-severity: warning # Treat all linter issues as warnings by default

linters-settings:
  revive:
    severity: warning # Treat all revive errors as warnings
    rules:
      - name: argument-limit
        severity: warning
        disabled: false
        exclude: [""]
        arguments: [1]
